language: java

jdk:
  - openjdk11
  - oraclejdk11


before_install:
    - echo `echo ${TRAVIS_JDK_VERSION} | grep -o "[0-9]\+"`

install:
    - mvn install -Djava.version=`echo ${TRAVIS_JDK_VERSION} | grep -o "[0-9]\+"` -DskipTests=true -Dmaven.javadoc.skip=true -B -V

script:
    - mvn -Dspring.profiles.active=test test -Djava.version=`echo ${TRAVIS_JDK_VERSION} | grep -o "[0-9]\+"`

