language: java

jdk:
  - oraclejdk8
  - openjdk8
  - openjdk11
  - oraclejdk11


before_install:
    - echo ${TRAVIS_JDK_VERSION}

script:
    - mvn -Dspring.profiles.active=test test -Djava.version=`echo ${TRAVIS_JDK_VERSION} | grep -o "[0-9]\+"`

